In [6]:
import os
import glob
import pandas as pd
os.chdir("../citi_summer_data_2019")

In [7]:
extension3 = 'csv'
all_filenames3 = [i for i in glob.glob('*.{}'.format(extension3))]

In [8]:
all_filenames3

['201906-citibike-tripdata.csv',
 '201907-citibike-tripdata.csv',
 '201905-citibike-tripdata.csv']

In [9]:
combined_csv3 = pd.concat([pd.read_csv(f) for f in all_filenames3 ])

In [10]:
combined_csv3.to_csv( "combined_city_2019.csv", index=False, encoding='utf-8-sig')

In [11]:
combined_csv3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1

In [12]:
df_2019 = combined_csv3.drop(columns=['stoptime', 'end station name', 'end station latitude', 'end station longitude'])

In [13]:
df_2019.head()

,tripduration,starttime,start station id,start station name,start station latitude,start station longitude,end station id,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,229.0,Great Jones St,40.727434,-73.993790,326.0,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,31290,Subscriber,1973,1

In [14]:
df_2019.to_csv( "df_citi_summer_2019.csv", index=False, encoding='utf-8-sig')